name: 'Get & Cache dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3 # you can use other actions in your custom actions, and you DON'T need to specify shell
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash # you must add this, if you are not using an action